### ISSUE TITLE
esm not found when running npm run setup

### ISSUE THREAD

**Issue by dominwong4** [fauna-labs/faunadb-auth-skeleton-with-auth0#1]
`> node -r esm ./scripts/setup.js local

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'esm'
Require stack:
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1217:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:447:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:75:3)
    at internal/main/run_main_module.js:7:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fauna-queries@1.0.0 setup: `node -r esm ./scripts/setup.js local`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fauna-queries@1.0.0 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2020-11-19T04_01_31_694Z-debug.log`

I have to run npm i esm to fix this

**Comment by fauna-brecht** [comment]
Thanks, I'll make sure to add esm to the package.json

**Comment by dominwong4** [comment]
Thanks!

**Comment by fauna-brecht** [comment]
Updated the README, the package.json in the root folder already contained the library, but I said it was optional in the README which is clearly not the case so thanks for letting me know. 
To keep the commit history clean (since I still can at this point) I force updated the commits so please reclone or force pull in case you check it out. I would advise in each case to wait for the blog post which should come out somewhere next week :)
